# this is a config for https://github.com/saleor/configurator
pageTypes:
  - name: Store
    attributes:
      - name: Store Offers
        inputType: REFERENCE
        entityType: PAGE
  - name: Offer
    attributes:
      - name: Offer Variant
        inputType: REFERENCE
        entityType: PRODUCT_VARIANT
      - name: Offer Price
        inputType: PLAIN_TEXT
